from .Gelu import QuantGelu
from .LayerNorm import QuantLayerNorm
from .MatMul import QuantMatMul
from .Linear import QuantLinear
from .Softmax import QuantSoftmax
from .Act import QuantAct
from .ElemAdd import QuantElemAdd
from .ElemRightShift import QuantElemRightShift
from .Conv2d import QuantConv2d
from .Base import Hooks
